services:
  mysite-dev:
    build:
      context: .
      target: development #指定构建开发阶段
    ports:
      - "3100:5173"
    volumes:
      - .:/app #挂载代码，实现热重载
      - /app/node_modules # 避免容器内的node_modules被覆盖
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true   # ✅ 添加此行
      - CHOKIDAR_INTERVAL=5000      # 可选，轮询间隔（毫秒）
  mysite-prod:
    build:
      context: .
      target: production # 指定构建生产阶段
    ports:
      - "3200:80"
    environment:
      - NODE_ENV=production